'use client'

import { useState } from 'react'
import { motion } from 'framer-motion'
import { Download, FileText, ArrowLeft, CheckCircle } from 'lucide-react'
import { useRouter } from 'next/navigation'
import ProtectedPage from '../../components/ProtectedPage'

export default function LedgerPage() {
  const router = useRouter()
  const [isDownloading, setIsDownloading] = useState(false)
  const [downloaded, setDownloaded] = useState(false)

  const handleDownloadLedger = async () => {
    setIsDownloading(true)

    try {
      // Dynamic import of jsPDF to avoid SSR issues
      const { jsPDF } = await import('jspdf')

      const doc = new jsPDF()

      // Title
      doc.setFontSize(20)
      doc.setFont(undefined, 'bold')
      doc.text('Sample Ledger Report', 105, 20, { align: 'center' })

      // Date
      doc.setFontSize(10)
      doc.setFont(undefined, 'normal')
      const today = new Date().toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric'
      })
      doc.text(`Generated: ${today}`, 105, 30, { align: 'center' })

      // Line separator
      doc.setLineWidth(0.5)
      doc.line(20, 35, 190, 35)

      // Sample data
      doc.setFontSize(12)
      doc.setFont(undefined, 'bold')
      doc.text('Transaction Details', 20, 45)

      // Table headers
      doc.setFontSize(10)
      doc.setFont(undefined, 'bold')
      let yPos = 55
      doc.text('Date', 20, yPos)
      doc.text('Description', 50, yPos)
      doc.text('Debit', 120, yPos)
      doc.text('Credit', 150, yPos)
      doc.text('Balance', 175, yPos)

      // Line under headers
      doc.setLineWidth(0.3)
      doc.line(20, yPos + 2, 190, yPos + 2)

      // Sample transactions
      doc.setFont(undefined, 'normal')
      const transactions = [
        { date: '2026-02-01', desc: 'Opening Balance', debit: '', credit: '', balance: '10,000.00' },
        { date: '2026-02-05', desc: 'Cash Sales', debit: '5,500.00', credit: '', balance: '15,500.00' },
        { date: '2026-02-07', desc: 'Supplier Payment', debit: '', credit: '2,300.00', balance: '13,200.00' },
        { date: '2026-02-10', desc: 'Cash Sales', debit: '3,200.00', credit: '', balance: '16,400.00' },
        { date: '2026-02-12', desc: 'Rent Payment', debit: '', credit: '1,500.00', balance: '14,900.00' },
        { date: '2026-02-14', desc: 'Cash Sales', debit: '4,800.00', credit: '', balance: '19,700.00' },
        { date: '2026-02-18', desc: 'Utility Bills', debit: '', credit: '800.00', balance: '18,900.00' },
        { date: '2026-02-20', desc: 'Cash Sales', debit: '6,100.00', credit: '', balance: '25,000.00' },
      ]

      yPos += 8
      transactions.forEach(txn => {
        doc.text(txn.date, 20, yPos)
        doc.text(txn.desc, 50, yPos)
        doc.text(txn.debit, 120, yPos)
        doc.text(txn.credit, 150, yPos)
        doc.text(txn.balance, 175, yPos)
        yPos += 7
      })

      // Summary section
      yPos += 10
      doc.setLineWidth(0.5)
      doc.line(20, yPos, 190, yPos)
      yPos += 10

      doc.setFont(undefined, 'bold')
      doc.setFontSize(11)
      doc.text('Summary', 20, yPos)

      yPos += 8
      doc.setFontSize(10)
      doc.setFont(undefined, 'normal')
      doc.text('Total Debits:', 120, yPos)
      doc.text('19,600.00', 175, yPos)

      yPos += 6
      doc.text('Total Credits:', 120, yPos)
      doc.text('4,600.00', 175, yPos)

      yPos += 6
      doc.setFont(undefined, 'bold')
      doc.text('Net Balance:', 120, yPos)
      doc.text('25,000.00', 175, yPos)

      // Footer
      yPos = 280
      doc.setFontSize(8)
      doc.setFont(undefined, 'italic')
      doc.text('This is a sample ledger report generated by BizPOS', 105, yPos, { align: 'center' })
      doc.text('For demonstration purposes only', 105, yPos + 5, { align: 'center' })

      // Save the PDF
      doc.save('Sample-Ledger-Report.pdf')

      setDownloaded(true)
      setTimeout(() => {
        setDownloaded(false)
      }, 3000)
    } catch (error) {
      console.error('Error generating PDF:', error)
      alert('Failed to generate PDF. Please try again.')
    } finally {
      setIsDownloading(false)
    }
  }

  return (
    <ProtectedPage>
      <div className="min-h-screen bg-gradient-to-br from-blue-50 via-indigo-50 to-purple-50 dark:from-gray-900 dark:via-gray-800 dark:to-gray-900 p-8">
        <div className="max-w-4xl mx-auto">
          {/* Back button */}
          <motion.button
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            onClick={() => router.push('/dashboard')}
            className="mb-8 flex items-center gap-2 text-gray-600 dark:text-gray-300 hover:text-gray-900 dark:hover:text-white transition-colors"
          >
            <ArrowLeft className="w-5 h-5" />
            <span className="font-medium">Back to Dashboard</span>
          </motion.button>

          {/* Main card */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 }}
            className="bg-white dark:bg-gray-800 rounded-3xl shadow-2xl overflow-hidden"
          >
            {/* Header */}
            <div className="bg-gradient-to-r from-blue-600 via-indigo-600 to-purple-600 p-8 text-white">
              <motion.div
                initial={{ scale: 0 }}
                animate={{ scale: 1 }}
                transition={{ delay: 0.2, type: "spring" }}
                className="w-20 h-20 mx-auto mb-4 bg-white/20 backdrop-blur-sm rounded-2xl flex items-center justify-center"
              >
                <FileText className="w-10 h-10" />
              </motion.div>
              <h1 className="text-3xl font-bold text-center mb-2">Sample Ledger Report</h1>
              <p className="text-center text-blue-100">
                Download a sample ledger report to see the format
              </p>
            </div>

            {/* Content */}
            <div className="p-8">
              <div className="space-y-6">
                {/* Info section */}
                <div className="bg-gradient-to-r from-blue-50 to-indigo-50 dark:from-gray-700 dark:to-gray-600 rounded-2xl p-6">
                  <h2 className="text-xl font-bold text-gray-900 dark:text-white mb-4">
                    What's Included?
                  </h2>
                  <ul className="space-y-3">
                    <li className="flex items-start gap-3">
                      <CheckCircle className="w-5 h-5 text-green-500 flex-shrink-0 mt-0.5" />
                      <span className="text-gray-700 dark:text-gray-200">
                        <strong>Transaction Details:</strong> Date, description, debit, credit, and running balance
                      </span>
                    </li>
                    <li className="flex items-start gap-3">
                      <CheckCircle className="w-5 h-5 text-green-500 flex-shrink-0 mt-0.5" />
                      <span className="text-gray-700 dark:text-gray-200">
                        <strong>Financial Summary:</strong> Total debits, credits, and net balance
                      </span>
                    </li>
                    <li className="flex items-start gap-3">
                      <CheckCircle className="w-5 h-5 text-green-500 flex-shrink-0 mt-0.5" />
                      <span className="text-gray-700 dark:text-gray-200">
                        <strong>Professional Format:</strong> Clean, organized layout suitable for business use
                      </span>
                    </li>
                    <li className="flex items-start gap-3">
                      <CheckCircle className="w-5 h-5 text-green-500 flex-shrink-0 mt-0.5" />
                      <span className="text-gray-700 dark:text-gray-200">
                        <strong>Ready to Print:</strong> Optimized PDF format for easy printing and sharing
                      </span>
                    </li>
                  </ul>
                </div>

                {/* Note */}
                <div className="bg-yellow-50 dark:bg-yellow-900/20 border border-yellow-200 dark:border-yellow-800 rounded-xl p-4">
                  <p className="text-sm text-yellow-800 dark:text-yellow-200">
                    <strong>Note:</strong> This is a sample report with demonstration data.
                    Your actual ledger reports will contain your real transaction data.
                  </p>
                </div>

                {/* Download button */}
                <div className="pt-4">
                  <motion.button
                    whileHover={{ scale: 1.02 }}
                    whileTap={{ scale: 0.98 }}
                    onClick={handleDownloadLedger}
                    disabled={isDownloading}
                    className={`w-full py-4 px-6 rounded-xl font-semibold text-white shadow-lg transition-all duration-200 flex items-center justify-center gap-3 ${
                      isDownloading
                        ? 'bg-gray-400 cursor-not-allowed'
                        : downloaded
                        ? 'bg-green-500 hover:bg-green-600'
                        : 'bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-700 hover:to-indigo-700 hover:shadow-xl'
                    }`}
                  >
                    {isDownloading ? (
                      <>
                        <motion.div
                          animate={{ rotate: 360 }}
                          transition={{ duration: 1, repeat: Infinity, ease: "linear" }}
                        >
                          <Download className="w-6 h-6" />
                        </motion.div>
                        <span>Generating PDF...</span>
                      </>
                    ) : downloaded ? (
                      <>
                        <CheckCircle className="w-6 h-6" />
                        <span>Downloaded Successfully!</span>
                      </>
                    ) : (
                      <>
                        <Download className="w-6 h-6" />
                        <span>Download Sample Ledger</span>
                      </>
                    )}
                  </motion.button>
                </div>
              </div>
            </div>
          </motion.div>

          {/* Additional info */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 0.3 }}
            className="mt-6 text-center"
          >
            <p className="text-sm text-gray-600 dark:text-gray-400">
              Need help? Contact support or check the documentation for more information.
            </p>
          </motion.div>
        </div>
      </div>
    </ProtectedPage>
  )
}
